apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    name: yolo-torchserve-metrics
  name: yolo-torchserve-metrics
spec:
  endpoints:
  - interval: 30s
    port: "web"
    scheme: http
  selector:
    matchLabels:
      app: yolo
