apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: yolo-frontend
  name: yolo-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo-frontend
  strategy: {}
  template:
    metadata:
      labels:
        app: yolo-frontend
    spec:
      containers:
      - image: ghcr.io/kwkoo/kserve-yolo-frontend
        name: kserve-yolo-frontend
        ports:
        - name: http
          containerPort: 8080
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: yolo-frontend
  name: yolo-frontend
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: yolo-frontend
status:
  loadBalancer: {}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: yolo-frontend
  name: yolo-frontend
spec:
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  port:
    targetPort: 8080
  to:
    name: yolo-frontend
    weight: null
status: {}
