---
apiVersion: v1
stringData:
  AWS_ACCESS_KEY_ID: XXX
  AWS_SECRET_ACCESS_KEY: XXX
kind: Secret
metadata:
  labels:
    app: yolo
  annotations:
    serving.kserve.io/s3-endpoint: "minio.demo.svc:9000"
    serving.kserve.io/s3-usehttps: "0"
  name: kserve-secret
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: yolo
  name: kserve-sa
secrets:
- name: kserve-secret
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  labels:
    app: yolo
  name: yolo
spec:
  predictor:
    serviceAccountName: kserve-sa
    model:
      modelFormat:
        name: pytorch
      storageUri: s3://models
      protocolVersion: v2
    tolerations:
      - key: nvidia.com/gpu
        value: "True"
        effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: yolo-internal
  name: yolo-internal
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: metrics
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    serving.kserve.io/inferenceservice: yolo
  type: ClusterIP