apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    name: yolo-torchserve-metrics
  name: yolo-torchserve-metrics
spec:
  endpoints:
  - bearerTokenSecret:
      key: ""
    port: "torchserve"
    scheme: http
  namespaceSelector: {}
  selector:
    matchLabels:
      name: yolo-torchserve-metrics
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: yolo-torchserve-metrics
  name: yolo-torchserve-metrics
spec:
  ports:
  - name: torchserve
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    serving.kserve.io/inferenceservice: yolo
  type: ClusterIP
