apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    name: yolo-torchserve-metrics
  name: yolo-torchserve-metrics
spec:
  endpoints:
  - bearerTokenSecret:
      key: ""
    port: "torchserve"
    scheme: http
  namespaceSelector: {}
  selector:
    matchLabels:
      name: yolo-internal
